on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: 'Deploy cdk to aws stack 🚀'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: build go project
      - uses: actions/setup-go@v3
        working-directory: ./functions
        with:
          go-version: '1.19.3' # The Go version to download (if necessary) and use.
      - run: GOOS=linux GOARCH=amd64 go build -o main main.go
      - name: installing infrastructure dependencies
        working-directory: ./infra
        run: npm i
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: deploying website and infrastructure
        working-directory: ./infra
        run: |
          npm run cdk bootstrap
          npm run cdk synth
          npm run cdk deploy